### ISSUE TITLE
Document and publish provider to terraform registry 

### ISSUE THREAD

**Issue by evalsocket** [nirmata/terraform-provider-nirmata#22]

**Comment by JimBugwadia** [comment]
We will need to update the repo structure to match the expected layout. 

https://www.terraform.io/docs/registry/providers/docs.html

We also need to check the documentation.

**Comment by JimBugwadia** [comment]
Some tools to consider:

https://github.com/terraform-docs/terraform-docs

https://github.com/antonbabenko/pre-commit-terraform

https://itnext.io/terraform-enforcing-doc-generation-and-code-formatting-e7dc6098b3a0

**Comment by JimBugwadia** [comment]
On discussion with HashiCorp, the new process is to self-publish on https://registry.terraform.io/

For the docs, we need to follow the process described at: https://www.terraform.io/docs/registry/providers/docs.html

The complete process for managing a provider is at: https://www.terraform.io/docs/registry/providers/publishing.html#preparing-your-provider

**Comment by JimBugwadia** [comment]
Published at: https://github.com/nirmata/terraform-provider-nirmata
